# table config
model:
  schema: access
  user:
    table: user
    id: user_id
  role:
    table: role
    id: role_id
  confirm:
    table: confirm
    id: confirm_id
  # other config
  user
lock_time: 15;
